### ISSUE TITLE
API interaction / JSON getter

### ISSUE THREAD

**Issue by hullale** [OSU-CS492-W18/final-project-team-5#4]
Similar to[ OpenWeatherMapUtils.java ](https://github.com/OSU-CS492-W18/master-assignment-3/blob/master/app/src/main/java/com/example/android/lifecycleweather/utils/OpenWeatherMapUtils.java)
Also will need to implement a URL builder similar to[ NetworkUtils.java](https://github.com/OSU-CS492-W18/master-assignment-3/blob/master/app/src/main/java/com/example/android/lifecycleweather/utils/NetworkUtils.java)

Might need two of these files, one to find the route between two points, and one to find the elevation at a specific point. I assume this is more than a one man task.

**Comment by ozarowib** [comment]
Need to change Elevation API usage so it returns information for the full route
